### ISSUE TITLE
Issue on numpy

### ISSUE THREAD

**Issue by Gioier** [oliverphilcox/Spectra-Without-Windows#1]
Good morning, I am Giovanni and I'm trying to run your code in my PC. I am running the script "generate_mask" and at line 151 I get this error message:
File "generate_mask.py", line 151, in <module>
rescale = np.sum(randoms["WEIGHT"]).compute()*v_cell/np.sum(nbar_mask)
File "<__array_function__ internals>", line 5, in sum
TypeError: no implementation found for "numpy.sum" on types that implement __array_function__: [<class "nbodykit.base.catalog.ColumnAccessor">].
Do you have any idea of what this could be?
Thank you in advance.
Giovanni

**Comment by oliverphilcox** [comment]
Hi Giovanni!

Thanks for the question. This seems to be an issue to do with nbodykit (it's fine on my end). Are you running on linux? It might help to change line 151 to "np.sum(randoms["WEIGHT"].compute())*v_cell/np.sum(nbar_mask)". If that doesn't work, you could try updating your numpy / nbodykit versions.

Cheers,
Oliver

**Comment by Gioier** [comment]
Goode evening,
I tried your suggestions, but I still have this problem.
yes i use linux.
Ii found that the error appears also at line 157 of
"compute_pk_boss_randoms", when the code is computing alpha_ran.
I saw in the page of nbodykit.base.catalog "
https://nbodykit.readthedocs.io/en/latest/api/_autosummary/nbodykit.base.catalog.html#nbodykit.base.catalog.ColumnAccessor",

in the "sum" function "
https://nbodykit.readthedocs.io/en/latest/api/_autosummary/nbodykit.base.catalog.html#nbodykit.base.catalog.ColumnAccessor.sum"
there is written
"

This docstring was copied from numpy.ndarray.sum.

Some inconsistencies with the Dask version may exist.

Return the sum of the array elements over the given axis.

Refer to numpy.sum for full documentation."

So I tried to write this sum function instead of np.sum: the code doesn't
gives the error, but the computation of alpha_ran is very long,

after one hour it was still computing only that command, so I had to stop.

Is this long time normal for that computation? or maybe substituting no.sum
with sum actually doesn't compute it?

Thanks in advance

Giovanni

Il giorno ven 4 feb 2022 alle ore 20:24 Oliver Philcox <
***@***.***> ha scritto:

**Comment by oliverphilcox** [comment]
Hi Giovanni,

Thanks for the response. This definitely seems to be an issue to do with nbodykit / dask / numpy, and I think it must be to do with specific code versions, since it works fine for other linux users. 

Perhaps we should start with a simpler test.  After line 98, you could add ```np.sum(data['WEIGHT']).compute()``` and see if that computes. Other options to try would be ```data['WEIGHT'].sum()``` and ```np.sum(data['WEIGHT'].compute())```. 

Also, you could replace ```np.sum(randoms['WEIGHT']).compute()``` in line 149 with ```np.sum(random_w)```, since the code already managed to load the randoms in line 120. If things are still causing issue, it's worth seeing how large your random catalog is (try ```print(len(randoms))```). 

Cheers,
Oliver

**Comment by Gioier** [comment]
Dear Oliver,
Thank to your suggestions I have solved the problem, thank you!
If may ask I would have two passages that are not totally clear.
Your code need
- a uniform random particle catalog that is used to calculate the Fisher
and Bias term.
-a nbar grid to perform the covariance calculation.
I am analyzing a Euclid like catalog that has the  grids that reflects the
geometry of Euclid, so the majority of the cells in the nbar grid are zero
(except where there are the galaxies), so I have two questions:
-does the fact that the majority of the cells in the nbar grid could affect
the correct works of your code?
-the uniform catalog used, should reflect also the geometry of my Euclid
catalog? Because I saw that you run it only in a box volume divided into
grids, not accounting for a possible "geometry of a survey".
Thank you very much and sorry for the disturb.
Best regards
Giovanni


Il dom 6 feb 2022, 17:38 Oliver Philcox ***@***.***> ha
scritto:

**Comment by Gioier** [comment]
Hi Oliver,
I was wondering if the catalog that I am studying may affect the correct
run of the code, because I obtain an NON-invertible Fisher matrix, since
some raws are zeros.
I checked the code and I found that in the passage when I calculate
 "C_a_Cinv_diff" and "C_a_Ainv_diff"
 that is applying the "applyC_alpha" covariance matrix to
"C_inc_diff" and "Ainv_diff"
I obtain all the entries equal to zero.
the "applyC_alpha" needs both the nbar grids and the k-grids and r-grids.
I tried to run the code with another nbar (obtained by random values) but
the Fisher is not still invertible.
So could be that the k-grid and r-grid, obtained by my density catalog,
inside the "applyC_alpha" could bring a matrix with all zeros?
Thank in advance and sorry for the disturb
Giovanni

Il dom 27 feb 2022, 09:12 Giovanni Ieranò ***@***.***>
ha scritto:

**Comment by oliverphilcox** [comment]
Hi Giovanni,

Thanks for the messages! I reply to each point below:

> -does the fact that the majority of the cells in the nbar grid could affect
> the correct works of your code?
> -the uniform catalog used, should reflect also the geometry of my Euclid
> catalog? Because I saw that you run it only in a box volume divided into
> grids, not accounting for a possible "geometry of a survey".
 
It's normally the case that most of the cells in the nbar grid are zero; this is just a consequence of using a bigger wider grid than the survey volume. This shouldn't affect any internal workings - you'll just end up adding a load of zeros in places. The same was true for the BOSS survey this code was originally used for,

The uniform catalog should *not* reflect the Euclid geometry. That catalog, call it **a**, is included to allow the Fisher matrix to be rewritten as an expectation of a pair of vectors. The only requirement for this is that the (inverse) covariance of **a** catalog (denoted Ainv in the code, and the recent paper), should be precisely known - for this reason I use a uniform catalog for a, which is applicable regardless of the survey geometry. Again, this was used in the BOSS analysis with a very non-uniform window function.

>  I obtain an NON-invertible Fisher matrix, since
some raws are zeros.
I checked the code and I found that in the passage when I calculate
 "C_a_Cinv_diff" and "C_a_Ainv_diff"
 that is applying the "applyC_alpha" covariance matrix to
"C_inc_diff" and "Ainv_diff"
I obtain all the entries equal to zero.
the "applyC_alpha" needs both the nbar grids and the k-grids and r-grids.
I tried to run the code with another nbar (obtained by random values) but
the Fisher is not still invertible.
So could be that the k-grid and r-grid, obtained by my density catalog,
inside the "applyC_alpha" could bring a matrix with all zeros?

This shouldn't happen... C_a_Cinv_diff is the result of applying the C_alpha operator / matrix to the map Cinv_diff (and likewise for Ainv_diff). The operation of C_alpha on a map **x** is something like IFT[Theta(**k**)FT[n(**r**)x(**r**)]], where Theta(**k**) is some **k**-space filter. It might be worth checking what's going on in each part of the C_alpha function. It sounds like you're getting n(**r**)x(**r**) = **0** or something like that, which would be very strange (and imply that there's no overlap between data and nbar!) 
 
Let me know if this doesn't solve things!

~ Oliver

**Comment by Gioier** [comment]
Hi Oliver,
I have solved the problem.
With my catalog I have to put kmax=1*k_nyquist, otherwise I have some
problem with the theta function that for some bins gives all FALSE values
and so one raws of the Fisher matrix is zero and It is not invertible.

I have however one question concerning the script that calculate the Fisher
and Bias term.
You run a uniform random simulation that you use to calculate the bias and
the Fisher matrix, to unbiased the power spectrum estimates.
The first term is due to poissonian noise, while we need the second to
cancel the effect of the window function.
So this is why you said that the catalog hasn't to respect the survey
geometry, because the "effect" of the window function contained in the
Fisher information are inside the matrices operations applied on the
uniform catalog, is this right?
In fact in the matrix operation you are accounting for the nbar_weight that
contains the window due to the geometry of the system.
I would like if you coorect me if I am wrong, in order to understand better.
Thank another time for your help.
Giovanni

Il mar 1 mar 2022, 00:49 Oliver Philcox ***@***.***> ha
scritto:

**Comment by oliverphilcox** [comment]
Hi Giovanni,

> I have solved the problem.
> With my catalog I have to put kmax=1*k_nyquist, otherwise I have some
> problem with the theta function that for some bins gives all FALSE values
> and so one raws of the Fisher matrix is zero and It is not invertible.
> 

Great! This makes sense: you can only compute the power spectrum up to the Nyquist frequency, else there are no elements with the correct k. Usually it's desirable to set kmax a little below k_Nyquist to avoid any aliasing effects, but that doesn't seem to have a major impact here.

> I have however one question concerning the script that calculate the Fisher
> and Bias term.
> You run a uniform random simulation that you use to calculate the bias and
> the Fisher matrix, to unbiased the power spectrum estimates.
> The first term is due to poissonian noise, while we need the second to
> cancel the effect of the window function.
> So this is why you said that the catalog hasn't to respect the survey
> geometry, because the "effect" of the window function contained in the
> Fisher information are inside the matrices operations applied on the
> uniform catalog, is this right?

> In fact in the matrix operation you are accounting for the nbar_weight that
> contains the window due to the geometry of the system.

Yes, that's absolutely correct! All the knowledge of the survey is in the nbar maps that go into the C_alpha and C^-1 functions; the uniform catalog is just used as a trick to allow for efficient computation of the matrix traces.

All the best,
Oliver

**Comment by Gioier** [comment]
Hi Oliver,
I am using your code and i have an issue and I would like to know what do
you think.

I attach the Power Spectra that I am obtaining ( file
"Power_spectra_mycode") and as you can see for large k I obtain some P2 and
P4 values that are incredibly large.
I am measuring the Power Spectrum of a survey that is a layer of a sphere
between z=0.9 and z=1.1, with the observer in the center.
To see where these strange values come from I have plotted the q_alpha
estimates that I obtain, that are shown in the ("q_alpha_mycode") and for
comparison I attach also the q_alpha from your code
("q_alpha_BOSS_code"). As you can see the first values of q_alpha that are
related to the P2 and P4 parts (in my code at 0.1 and 0.2 ) are larger than
yours, maybe this
create the problem.
I underlying that I am using your code without being modified ( a part from
the input catalog obviously), and I have tried it to analyze the BOSS
catalog and with it, it works properly.
So I don't know what it could be.
I very appreciate if you could give me your opinion.
Thank in advance.
Giovanni



Il giorno mer 2 mar 2022 alle ore 16:22 Oliver Philcox <
***@***.***> ha scritto:

**Comment by Gioier** [comment]
It's strange because the wrong behavior it's only in the small k, as the
problem would be only in the first spherical harmonics.

Il giorno sab 19 mar 2022 alle ore 09:46 Giovanni Ieranò <
***@***.***> ha scritto:

**Comment by oliverphilcox** [comment]
Hi Giovanni,

Thanks for the message. Could you email me the plots at ohep2@cantab.ac.uk? I can't see them currently. Also, at what k are the problems appearing? Is this close to the Nyquist frequency?

Best,
Oliver

**Comment by Gioier** [comment]
I have sent them to the email, the problem are at small k for P2 and P4
that have very huge values.
Giovanni

Il sab 19 mar 2022, 18:02 Oliver Philcox ***@***.***> ha
scritto:

**Comment by Gioier** [comment]
Can you see them properly or do you want that I send them another time?
It's not a problem
Giovanni

Il sab 19 mar 2022, 18:12 Giovanni Ieranò ***@***.***>
ha scritto:
