### ISSUE TITLE
generate_mask.py file being killed while execution

### ISSUE THREAD

**Issue by sourav1729** [oliverphilcox/Spectra-Without-Windows#5]
Hi,
    I was trying to plot pk and bk multipoles . As documented, to compute that, first I need to create the background density map n(r) using generate_mask.py. 
 I was trying with just 100 mocks and boss_nC.param file. After loading the mask, data and random files the script is suddenly killed. I don't understand whether the problem is associated with nbodykit or pyfits. 
I have attached here the screenshot of the outputs while executing the script.
I appreciate any comments or views in this regards.
Thanks & regards.
![Screenshot](https://github.com/oliverphilcox/Spectra-Without-Windows/assets/89576482/fad5e797-f74b-494b-bc29-fef00f9da9b2)

**Comment by oliverphilcox** [comment]
Thanks for the interest in the code! Firstly, I should note that this code is about to be deprecated in favor of a much more advanced / flexible code [PolyBin3D](https://github.com/oliverphilcox/PolyBin3D), that I'd recommend using from now on! The code and documentation is finished, though the paper isn't quite yet done!

Regarding your problem: this is just indicating that the process has run out of memory. If you're running the code on a cluster, you'll need to ask for larger memory. 

Hope this helps!
~ Oliver
